apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastfood-deployment
  labels:
    app: fastfood
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastfood
  template:
    metadata:
      labels:
        app: fastfood
    spec:
      containers:
        - name: fastfood
          image: brunoleonardomg/fastfood-api:v2.0
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: fastfood-secret
                  key: DB_HOST
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: fastfood-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fastfood-secret
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: fastfood-secret
                  key: DB_NAME
