apiVersion: v1
kind: Secret
metadata:
  name: fastfood-secret
  namespace: default
type: Opaque
data:
  DB_HOST: bXlzcWwtc2VydmljZQ==
  DB_USERNAME: cm9vdA==
  DB_PASSWORD: YWRtaW4=
  DB_NAME: ZmFzdGZvb2Q=
