apiVersion: v1
kind: Service
metadata:
  name: fastfood-service
  namespace: default
spec:
  selector:
    app: fastfood
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
